<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/public/css/reset.css')
                        ->prependStylesheet($this->basePath() . '/public/css/960.css')
                        ->prependStylesheet($this->basePath() . '/public/css/text.css')
                        ->prependStylesheet($this->basePath() . '/public/css/style.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap.min.css') 
                        ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/public/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/public/js/jquery.min.js')
            ->prependFile($this->basePath() . '/public/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/public/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
       
        <header>
            <div class="container_16">
                <!-- <div class="grid_16 top-nav">
                    <a class="lang" href="#"><img src="<?php echo $this->basePath('/public/img')?>/vn.png"/></a>
                    <a class="lang" href="#"><img src="<?php echo $this->basePath('/public/img')?>/uk.png"/></a>
                    <span class="hotline">Hotline:<b>0123 456 789</b></span>
                </div> -->
                <div class="grid_4 logo">
                    <a href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('/public/img/fashion-logo.png') ?>"/></a>
                </div>
                <div class="grid_6 search_box">
                    <input type="text" placeholder="search" />
                </div>
                <div class="grid_6 right_col">
                    <div class="account">
                        <a class="signin" href="#">Sign in</a>
                        <a class="signup" href="#">Sign up</a>
                    </div>
                    <div class="cart_box">
                        Giỏ hàng <b class="quantity">0</b>
                    </div>
                </div>
            </div><!--/container_16-->
        </header>
        <div id="main-menu">
            <div class="container_16">
                <div class="grid_16">
                    <ul>
                        <li><a href="">Women</a>
                            <ul>
                                <li><a href="">Donec lobortis</a></li>
                                <li><a href="">pulvinar laoreet</a>
                                    <ul>
                                        <li><a href="">Donec lobortis</a></li>
                                        <li><a href="">pulvinar laoreet</a></li>
                                        <li><a href=""> Nullam vehicula ligula</a></li>
                                        <li><a href="">Vestibulum vel neque</a></li>
                                        <li><a href="">Maecenas felis turpis</a></li>
                                        <li><a href="">Suspendisse accumsan</a></li>
                                        <li><a href="">Duis quis ullamcorper</a></li>
                                        <li><a href="">Nulla varius accumsan nisl</a></li>
                                    </ul>
                                </li>
                                <li><a href=""> Nullam vehicula ligula</a></li>
                                <li><a href="">Vestibulum vel neque</a></li>
                                <li><a href="">Maecenas felis turpis</a></li>
                                <li><a href="">Suspendisse accumsan</a></li>
                                <li><a href="">Duis quis ullamcorper</a></li>
                                <li><a href="">Nulla varius accumsan nisl</a></li>
                            </ul>
                        </li>
                        <li><a href="">Men</a></li>
                        <li><a href="">Shoes</a></li>
                        <li><a href="">Skirt</a></li>
                    </ul>
                </div>
            </div><!--/container_16-->
        </div><!--/main-menu-->
        <div class="container">
            <div class="container_16">
            <?php echo $this->content; ?>
            </div><!--/container_16-->
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
